-- =============================================================================
-- 20260927000002_create_applications.sql
--
-- Step 7 — the applicant's own application record: the row an "Apply Now" click
-- creates, and the anchor every later step hangs off (form saves, document
-- upload, officer review, decision).
--
-- IMPORTANT — this table already exists in the live project
-- --------------------------------------------------------
-- `applications` is not created by any file in supabase/migrations; like
-- `applicant_profiles` and `applicant_documents` it predates the migration
-- folder and was made directly in the Supabase project. Its real columns were
-- read back from the live PostgREST schema, and they are:
--
--     id, applicant_id, scheme_id, status, created_at, updated_at,
--     application_number, submitted_at
--
-- Note what is NOT there: there is no `application_id` column. The portal's
-- existing human-readable reference convention on this table is
-- `application_number`, so that is what this migration fills in and what the UI
-- navigates by. A `create table if not exists` here would have been a silent
-- no-op against the real table, so this migration is ALTER-only and every
-- statement is idempotent.
--
-- What this migration adds, and why
--   1. set_application_reference() — a BEFORE INSERT trigger that mints
--      application_number in the database, mirroring
--      public.set_applicant_reference() (20260926090100) which does the same for
--      applicant_profiles.applicant_id. Minting it in the trigger means the
--      reference is generated by the same clock and the same transaction that
--      inserts the row, and is persisted with it — not held in React state.
--   2. A unique constraint on (applicant_id, scheme_id). This is the real
--      duplicate guard. "Check then insert" in the browser cannot stop two
--      simultaneous clicks from both passing the check; a unique index can. The
--      service treats a 23505 on insert as "a concurrent click won" and re-reads
--      the winner's row, so both callers converge on one application.
--   3. Row level security, so an applicant can only ever see and write their own
--      applications, and cannot forge somebody else's applicant_id.
--
-- applicant_id is a uuid owned by the applicant_profiles row — the same subject
-- public.current_applicant_id() returns, and the same subject applicant_documents
-- is scoped by — NOT auth.users(id). The frontend never supplies it: it resolves
-- the applicant from the Supabase session, and RLS re-checks independently.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Human-readable reference
--
-- Idempotent: the trigger is dropped and recreated so re-running the migration
-- cannot stack two BEFORE INSERT triggers on the same table.
-- -----------------------------------------------------------------------------
create or replace function public.set_application_reference()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.application_number is null or new.application_number = '' then
    new.application_number := 'APP-' || to_char(now(), 'YYYY') || '-'
      || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_application_reference on public.applications;
create trigger set_application_reference
  before insert on public.applications
  for each row
  execute function public.set_application_reference();

-- -----------------------------------------------------------------------------
-- 1b. Backfill legacy rows
--
-- This runs here, deliberately BEFORE the updated_at trigger in section 2 is
-- created. Any UPDATE at all would fire that trigger and stamp every legacy row
-- with the migration's clock, quietly destroying the real "last updated" values
-- that the officer-facing screens read. Backfilling first keeps them honest.
--
-- Rows inserted from here on are covered by the trigger and need nothing. This
-- only rescues rows that predate it, which is why it is a one-shot update and
-- not a permanent rule.
-- -----------------------------------------------------------------------------
update public.applications
set application_number = 'APP-' || to_char(now(), 'YYYY') || '-'
  || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
where application_number is null or application_number = '';


-- -----------------------------------------------------------------------------
-- 2. updated_at
--
-- The live table already carries updated_at, but nothing guarantees it moves.
-- A second BEFORE UPDATE trigger is harmless (the reference trigger only fires on
-- INSERT) and makes the column trustworthy for the officer-facing "last updated".
-- -----------------------------------------------------------------------------
create or replace function public.set_applications_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_applications_updated_at on public.applications;
create trigger set_applications_updated_at
before update on public.applications
for each row
execute function public.set_applications_updated_at();

-- -----------------------------------------------------------------------------
-- 3. Constraints
--
-- Added only when absent, so this migration is safe to run against a project
-- where an operator has already added them by hand. Postgres has no
-- `add constraint if not exists`, hence the pg_constraint guard.
--
-- application_number is the value the applicant is shown and quotes, so two
-- applications must never share it even if the 8 hex characters ever collided.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.applications'::regclass
      and conname = 'applications_applicant_scheme_unique'
  ) then
    -- Pre-flight: a duplicate pair already in the table would make this fail.
    -- Better to say so plainly than to abort the whole migration halfway.
    if exists (
      select 1 from public.applications
      group by applicant_id, scheme_id
      having count(*) > 1
    ) then
      raise exception
        'Cannot enforce one-application-per-scheme: public.applications already holds duplicate (applicant_id, scheme_id) pairs. Resolve them first.';
    end if;

    alter table public.applications
      add constraint applications_applicant_scheme_unique
      unique (applicant_id, scheme_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.applications'::regclass
      and conname = 'applications_application_number_unique'
  ) then
    -- Section 1b backfilled null and empty references, so this should find
    -- nothing. It is kept as a cheap assertion rather than removed, because a
    -- silent skip here would mean uniqueness was never enforced at all.
    if exists (
      select 1 from public.applications
      where application_number is null or application_number = ''
    ) then
      raise exception
        'Cannot enforce a unique application_number: public.applications still has rows with a null or empty reference after backfill.';
    end if;

    alter table public.applications
      add constraint applications_application_number_unique
      unique (application_number);
  end if;
end;
$$;

comment on column public.applications.application_number is
  'Human-readable reference shown to the applicant and quoted by officers, e.g. APP-2026-A1B2C3D4. Minted by set_application_reference() in the database and persisted with the row. Display only: the application form is routed by the id primary key, because a reference written by anything other than this trigger would be an unconfirmed format. See src/lib/applicationHandle.ts.';

comment on table public.applications is
  'Applicant applications to scholarship schemes. One row per applicant per scheme (applications_applicant_scheme_unique).';

-- -----------------------------------------------------------------------------
-- 4. Foreign keys
--
-- This is the relationship the rest of the portal hangs off: an application
-- belongs to exactly one applicant_profiles row and exactly one scheme. All
-- four keys were confirmed to be uuid against the live schema rather than
-- assumed — applications.applicant_id, applications.scheme_id,
-- applicant_profiles.id and schemes.id — so these constraints are type-correct.
--
-- Added NOT VALID on purpose, and it matters. These columns predate this
-- migration and were made by hand in the Supabase project, so existing rows may
-- already hold ids that no longer resolve. A plain ADD CONSTRAINT validates the
-- whole table and aborts the migration on the first orphan, which would take
-- the reference trigger, the unique constraints and the RLS policies down with
-- it. NOT VALID enforces every new and updated row immediately, and leaves the
-- historical rows for a deliberate cleanup once someone has looked at them:
--
--   alter table public.applications
--     validate constraint applications_applicant_id_fkey;
--
-- No ON DELETE action is declared. Removing a profile or a scheme must never
-- silently cascade into destroying an applicant's application record; that
-- decision belongs to whoever removes the parent, not to this migration.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.applications'::regclass
      and conname = 'applications_applicant_id_fkey'
  ) then
    alter table public.applications
      add constraint applications_applicant_id_fkey
      foreign key (applicant_id) references public.applicant_profiles(id) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.applications'::regclass
      and conname = 'applications_scheme_id_fkey'
  ) then
    alter table public.applications
      add constraint applications_scheme_id_fkey
      foreign key (scheme_id) references public.schemes(id) not valid;
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 5. Indexes
--
-- The unique constraints already index (applicant_id, scheme_id) and
-- application_number. These serve the two read paths the portal actually uses:
-- the applicant's own list ordered by recency, and the officer-side scheme view.
-- -----------------------------------------------------------------------------
create index if not exists idx_applications_applicant_created
  on public.applications(applicant_id, created_at desc);
create index if not exists idx_applications_scheme_id
  on public.applications(scheme_id);
create index if not exists idx_applications_status
  on public.applications(status);

-- -----------------------------------------------------------------------------
-- 6. Grants
--
-- anon gets nothing: an unauthenticated visitor must not be able to read or
-- create an application. authenticated gets the DML the apply flow needs and no
-- DELETE — a withdrawal is a status transition, so the audit trail survives.
-- (The admin policy in section 7 is `for all` and does permit DELETE; that is
-- deliberate for administrator use, and is the only role that can remove a row.)
-- -----------------------------------------------------------------------------
revoke all on table public.applications from anon;
grant select, insert, update on table public.applications to authenticated;

-- -----------------------------------------------------------------------------
-- 7. Row level security
--
-- Same shape as applicant_documents (20260926090200): the policy subject is
-- applicant_id compared to public.current_applicant_id(), a SECURITY DEFINER
-- function that resolves applicant_profiles.user_id = auth.uid(). Consequences:
--   * select on another applicant's row returns zero rows, not an error and not
--     a leak.
--   * insert naming another applicant_id violates WITH CHECK and is rejected by
--     Postgres, so a tampered request body cannot create an application for
--     somebody else even if the frontend were bypassed entirely.
--   * update cannot move a row to another applicant_id — same WITH CHECK.
-- Administrator access follows the project's existing model: profiles.role read
-- through public.current_profile_role().
--
-- Policies are dropped first because create policy has no OR REPLACE, and the
-- same drop-then-create shape is used throughout the existing RLS migration.
--
-- Note on how policies combine: Postgres ORs every policy that applies to a
-- command, so these are all additive. That is why the applicant policies stay
-- narrow — a broad one anywhere in the list would widen the net for everybody,
-- and a later policy could not narrow it again.
-- -----------------------------------------------------------------------------
alter table public.applications enable row level security;

drop policy if exists "applications_select_own" on public.applications;
create policy "applications_select_own" on public.applications
  for select to authenticated
  using (applicant_id = public.current_applicant_id());

drop policy if exists "applications_insert_own" on public.applications;
create policy "applications_insert_own" on public.applications
  for insert to authenticated
  with check (applicant_id = public.current_applicant_id());

drop policy if exists "applications_update_own" on public.applications;
create policy "applications_update_own" on public.applications
  for update to authenticated
  using (applicant_id = public.current_applicant_id())
  with check (applicant_id = public.current_applicant_id());

drop policy if exists "applications_admin_all" on public.applications;
create policy "applications_admin_all" on public.applications
  for all to authenticated
  using (public.current_profile_role() = 'admin')
  with check (public.current_profile_role() = 'admin');

revoke all on function public.set_application_reference() from public;
