-- =============================================================================
-- Applicant profile — structural extensions to the EXISTING profile tables.
--
-- The live database already contains these tables with a partial column set.
-- This migration is strictly ADDITIVE: it never drops or renames a column, so
-- existing rows, existing queries and the existing admin/scheme tables keep
-- working. Every statement is idempotent and can be re-run safely.
--
-- Canonical existing columns that this migration REUSES instead of duplicating:
--   applicant_profiles.mobile_number      (not "mobile")
--   applicant_profiles.aadhaar_last4      (masked display source)
--   income_details.annual_income          (not "family_annual_income")
--   current_courses.mode_of_study         (not "mode")
--   current_courses.institution_name      (free text) + new institution_id
--   current_courses.university_name       (free text) + new board_university
--   bank_details.account_number           (legacy plaintext — locked to NULL)
--   bank_details.ifsc_code                (not "ifsc")
-- =============================================================================

-- -----------------------------------------------------------------------------
-- profiles: the repo migration 20260925120000 was never applied to this project.
-- Re-assert it idempotently so the auth/role plumbing the frontend depends on
-- (profiles.role, current_profile_role) actually exists.
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'applicant' check (role in ('applicant', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.set_profiles_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_profiles_updated_at();

-- -----------------------------------------------------------------------------
-- applicant_profiles — extend with the personal-detail fields the profile needs.
-- -----------------------------------------------------------------------------
alter table public.applicant_profiles
  add column if not exists full_name text,
  add column if not exists email text,
  add column if not exists applicant_full_name_as_per_marksheet text,
  add column if not exists parent_guardian_mobile text,
  add column if not exists aadhaar_masked text,
  add column if not exists aadhaar_fingerprint text,
  add column if not exists aadhaar_verified_at timestamptz,
  add column if not exists completeness_percent smallint,
  add column if not exists profile_status text,
  add column if not exists last_saved_at timestamptz;

comment on column public.applicant_profiles.aadhaar_fingerprint is
  'Salted SHA-256 of the normalised Aadhaar, used only for duplicate detection. Not reversible; the full Aadhaar is never stored.';
comment on column public.applicant_profiles.aadhaar_last4 is
  'Last 4 digits of the Aadhaar, used to render the masked value (XXXX XXXX 1234).';
comment on column public.applicant_profiles.applicant_id is
  'Human-readable applicant reference generated by set_applicant_reference().';

-- -----------------------------------------------------------------------------
-- domicile_details
-- -----------------------------------------------------------------------------
alter table public.domicile_details
  add column if not exists is_maharashtra_domicile boolean,
  add column if not exists has_domicile_certificate boolean,
  add column if not exists certificate_source text,
  add column if not exists certificate_holder_name text,
  add column if not exists issuing_authority text,
  add column if not exists date_of_issue date,
  add column if not exists document_id uuid references public.applicant_documents(id) on delete set null;

-- -----------------------------------------------------------------------------
-- income_details
-- -----------------------------------------------------------------------------
alter table public.income_details
  add column if not exists has_income_certificate boolean,
  add column if not exists certificate_source text,
  add column if not exists barcode text,
  add column if not exists document_id uuid references public.applicant_documents(id) on delete set null;

-- -----------------------------------------------------------------------------
-- personal_eligibility
-- -----------------------------------------------------------------------------
alter table public.personal_eligibility
  add column if not exists is_salaried boolean,
  add column if not exists job_type text,
  add column if not exists is_disabled boolean,
  add column if not exists disability_type text,
  add column if not exists has_disability_certificate boolean,
  add column if not exists disability_certificate_number text,
  add column if not exists disability_document_id uuid references public.applicant_documents(id) on delete set null,
  add column if not exists siblings_count smallint;

-- -----------------------------------------------------------------------------
-- caste_details
-- -----------------------------------------------------------------------------
alter table public.caste_details
  add column if not exists sub_caste text,
  add column if not exists has_caste_certificate boolean,
  add column if not exists certificate_source text,
  add column if not exists certificate_holder_name text,
  add column if not exists date_of_issue date,
  add column if not exists document_id uuid references public.applicant_documents(id) on delete set null;

-- -----------------------------------------------------------------------------
-- address_details
-- -----------------------------------------------------------------------------
alter table public.address_details
  add column if not exists permanent_address text,
  add column if not exists permanent_village text,
  add column if not exists same_as_permanent boolean not null default true,
  add column if not exists correspondence_address text,
  add column if not exists correspondence_village text;

-- -----------------------------------------------------------------------------
-- parent_guardian_details
-- -----------------------------------------------------------------------------
alter table public.parent_guardian_details
  add column if not exists father_alive boolean,
  add column if not exists father_salaried boolean,
  add column if not exists mother_alive boolean,
  add column if not exists mother_salaried boolean,
  add column if not exists guardian_required boolean,
  add column if not exists guardian_mobile text;

-- -----------------------------------------------------------------------------
-- bank_details
--   account_number is a legacy plaintext column. This migration only backfills
--   the display suffix. 20260926090100_applicant_profile_security.sql encrypts
--   any remaining plaintext value, clears it, and then locks the column to NULL
--   with a check constraint so a full account number can never be stored raw.
-- -----------------------------------------------------------------------------
alter table public.bank_details
  add column if not exists aadhaar_linked boolean,
  add column if not exists account_number_last4 text,
  add column if not exists account_number_ciphertext text;

update public.bank_details
   set account_number_last4 = right(account_number, 4)
 where account_number is not null
   and account_number_last4 is null;

-- -----------------------------------------------------------------------------
-- current_courses
-- -----------------------------------------------------------------------------
alter table public.current_courses
  add column if not exists degree text,
  add column if not exists branch text,
  add column if not exists year_of_study smallint,
  add column if not exists semester smallint,
  add column if not exists admission_date date,
  add column if not exists course_duration_months smallint,
  add column if not exists is_professional boolean,
  add column if not exists cap_admission boolean,
  add column if not exists cap_application_number text,
  add column if not exists seat_type text,
  add column if not exists institute_state text,
  add column if not exists institute_district text,
  add column if not exists institute_taluka text,
  add column if not exists board_university text,
  add column if not exists course_level_id uuid,
  add column if not exists course_id uuid,
  add column if not exists branch_id uuid,
  add column if not exists institution_id uuid,
  add column if not exists university_id uuid,
  add column if not exists board_id uuid;

-- -----------------------------------------------------------------------------
-- applicant_qualifications
-- -----------------------------------------------------------------------------
alter table public.applicant_qualifications
  add column if not exists qualification_type text,
  add column if not exists degree text,
  add column if not exists subject text,
  add column if not exists status text,
  add column if not exists state text,
  add column if not exists admission_date date,
  add column if not exists result text,
  add column if not exists attempts smallint,
  add column if not exists course_duration_months smallint,
  add column if not exists class_grade text,
  add column if not exists mode text,
  add column if not exists has_gap boolean,
  add column if not exists gap_duration_months smallint,
  add column if not exists marksheet_document_id uuid references public.applicant_documents(id) on delete set null;

-- -----------------------------------------------------------------------------
-- hostel_details
-- -----------------------------------------------------------------------------
alter table public.hostel_details
  add column if not exists beneficiary_category text,
  add column if not exists state text,
  add column if not exists district text,
  add column if not exists taluka text,
  add column if not exists is_aided boolean,
  add column if not exists mess_available boolean,
  add column if not exists rent_per_month numeric(12, 2),
  add column if not exists certificate_document_id uuid references public.applicant_documents(id) on delete set null;

-- -----------------------------------------------------------------------------
-- applicant_documents — verification audit columns
-- -----------------------------------------------------------------------------
alter table public.applicant_documents
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by uuid references auth.users(id) on delete set null,
  add column if not exists remarks text,
  add column if not exists created_at timestamptz not null default now();

comment on table public.applicant_documents is
  'Metadata only. File bytes live in the private applicant-documents storage bucket; storage_path is never exposed to other applicants.';

-- -----------------------------------------------------------------------------
-- Column contract.
--
-- The live database already has most of these columns, but the completeness
-- engine in 20260926090100 and the profile services read every one of them. Any
-- column that is merely ASSUMED to exist turns a missing column into a hard
-- "column does not exist" failure inside a plpgsql function, where the error
-- message points at the function rather than at the gap. So the full set the
-- engine touches is asserted here.
--
-- `if not exists` makes this a no-op wherever the column is already present,
-- whatever its existing type. Nothing here can change a live column.
-- -----------------------------------------------------------------------------
alter table public.applicant_profiles
  add column if not exists aadhaar_last4 text,
  add column if not exists mobile_number text,
  add column if not exists date_of_birth date,
  add column if not exists gender text,
  add column if not exists religion text,
  add column if not exists marital_status text;

alter table public.domicile_details
  add column if not exists certificate_number text,
  add column if not exists issuing_authority text;

alter table public.income_details
  add column if not exists annual_income numeric(12, 2),
  add column if not exists certificate_number text,
  add column if not exists certificate_date date,
  add column if not exists issuing_authority text;

alter table public.caste_details
  add column if not exists category text,
  add column if not exists caste text,
  add column if not exists certificate_number text,
  add column if not exists issuing_authority text;

alter table public.address_details
  add column if not exists permanent_state text,
  add column if not exists permanent_district text,
  add column if not exists permanent_taluka text,
  add column if not exists permanent_pincode text,
  add column if not exists correspondence_state text,
  add column if not exists correspondence_district text,
  add column if not exists correspondence_taluka text,
  add column if not exists correspondence_pincode text;

alter table public.parent_guardian_details
  add column if not exists father_name text,
  add column if not exists father_occupation text,
  add column if not exists mother_name text,
  add column if not exists mother_occupation text,
  add column if not exists guardian_name text,
  add column if not exists guardian_relationship text,
  add column if not exists guardian_occupation text;

alter table public.bank_details
  add column if not exists bank_name text,
  add column if not exists account_holder_name text,
  add column if not exists ifsc_code text,
  add column if not exists branch_name text,
  add column if not exists account_type text;

alter table public.current_courses
  add column if not exists academic_year text,
  add column if not exists course_level text,
  add column if not exists course_name text,
  add column if not exists mode_of_study text;

alter table public.applicant_qualifications
  add column if not exists board_university text,
  add column if not exists passing_year smallint,
  add column if not exists percentage numeric(5, 2);

alter table public.hostel_details
  add column if not exists hostel_type text,
  add column if not exists hostel_name text,
  add column if not exists hostel_address text;
